/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jol.quickstart;

import org.openjdk.jol.info.*;
import org.openjdk.jol.vm.*;

public class App {
    static class Car {
        private int id;
        private String type;
        private double price;
        private char level;

        public Car(int id, String type, double price, char level) {
            this.id = id;
            this.type = type;
            this.price = price;
            this.level = level;
        }
    }

    public String getGreeting() {
        return "Hello Jol!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Car car = new Car(3, "Racing Car", 133.9, 'A');

        System.out.println(ClassLayout.parseInstance(car).toPrintable());

        int[] array = new int[3];
        array[0] = 11;
        array[1] = 22;
        array[2] = 33;
        System.out.println(ClassLayout.parseInstance(array).toPrintable());

        System.out.println("toString: " + car);
        System.out.println("VM.current.addressOf: " + VM.current().addressOf(car));
        System.out.println("hashCode: " + car.hashCode());
        System.out.println("identityHashCode(actually same as hashCode): " + System.identityHashCode(car));
    }
}

